INSERT INTO dive_trips (dive_site_id, boat_name, departure_time, return_time, capacity, seats_booked, price, status) VALUES
                                                                                                                         ((SELECT id FROM dive_sites WHERE name = 'Molasses Reef'),
                                                                                                                          'Reef Runner',  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 3 DAY),  INTERVAL 8 HOUR),  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 3 DAY),  INTERVAL 12 HOUR), 12, 0, 110.00, 'SCHEDULED'),
                                                                                                                         ((SELECT id FROM dive_sites WHERE name = 'Blue Heron Bridge'),
                                                                                                                          'Tide Chaser',  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 4 DAY),  INTERVAL 7 HOUR),  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 4 DAY),  INTERVAL 10 HOUR), 8,  0, 75.00,  'SCHEDULED'),
                                                                                                                         ((SELECT id FROM dive_sites WHERE name = 'Palancar Gardens'),
                                                                                                                          'Coral Queen',  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 6 DAY),  INTERVAL 9 HOUR),  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 6 DAY),  INTERVAL 14 HOUR), 16, 0, 135.00, 'SCHEDULED'),
                                                                                                                         ((SELECT id FROM dive_sites WHERE name = 'SS Thistlegorm'),
                                                                                                                          'Wreck Hunter', DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 8 DAY),  INTERVAL 6 HOUR),  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 8 DAY),  INTERVAL 15 HOUR), 10, 0, 195.00, 'SCHEDULED'),
                                                                                                                         ((SELECT id FROM dive_sites WHERE name = 'Great Blue Hole'),
                                                                                                                          'Deep Blue',    DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 10 DAY), INTERVAL 6 HOUR),  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 10 DAY), INTERVAL 16 HOUR), 6,  0, 260.00, 'SCHEDULED'),
                                                                                                                         ((SELECT id FROM dive_sites WHERE name = 'Molasses Reef'),
                                                                                                                          'Reef Runner',  DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 12 DAY), INTERVAL 13 HOUR), DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 12 DAY), INTERVAL 17 HOUR), 12, 0, 110.00, 'SCHEDULED');